#!/bin/bash
# Asset Embedding Script for Harmony
# Converts binary assets to C arrays using POSIX tools (od + awk)
# This script uses only POSIX-compliant tools for maximum portability

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
OUTPUT_DIR="$PROJECT_ROOT/src/platform/generated"
ASSETS_DIR="$PROJECT_ROOT/assets"

mkdir -p "$OUTPUT_DIR"

OUTPUT_FILE="$OUTPUT_DIR/embedded_assets.c"
HEADER_FILE="$OUTPUT_DIR/embedded_assets.h"

# Quiet mode - only output on error

# Generate header file
cat > "$HEADER_FILE" << 'EOF'
// Auto-generated by embed_assets.sh - DO NOT EDIT
#ifndef HARMONY_EMBEDDED_ASSETS_H
#define HARMONY_EMBEDDED_ASSETS_H

#include <stddef.h>
#include <stdint.h>

// Embedded Default Font
extern const uint8_t g_default_font_data[];
extern const size_t g_default_font_size;

// Embedded App Icon (PNG)
extern const uint8_t g_app_icon_data[];
extern const size_t g_app_icon_size;

// Helper to get embedded font
static inline const uint8_t* GetEmbeddedFontData(void) {
    return g_default_font_data;
}

static inline size_t GetEmbeddedFontSize(void) {
    return g_default_font_size;
}

// Helper to get embedded icon
static inline const uint8_t* GetEmbeddedIconData(void) {
    return g_app_icon_data;
}

static inline size_t GetEmbeddedIconSize(void) {
    return g_app_icon_size;
}

#endif // HARMONY_EMBEDDED_ASSETS_H
EOF

# Generate source file header
cat > "$OUTPUT_FILE" << 'EOF'
// Auto-generated by embed_assets.sh - DO NOT EDIT
#include "embedded_assets.h"

EOF

# Function to convert binary file to C array using od + awk
convert_to_c_array() {
    local input_file="$1"
    local array_name="$2"
    local size_name="$3"
    
    echo "// Embedded from: $input_file"
    echo "const uint8_t $array_name[] = {"
    
    # Use od to dump hex, then awk to format as C array with 12 bytes per line
    # od -An: no address, -v: no asterisks for repeated lines, -tx1: hex bytes
    od -An -v -tx1 "$input_file" | awk '
    BEGIN { count = 0; first = 1 }
    {
        for (i = 1; i <= NF; i++) {
            if (count % 12 == 0) {
                if (!first) printf "\n"
                printf "    "
            } else {
                printf " "
            }
            first = 0
            printf "0x%s," , $i
            count++
        }
    }
    END { if (!first) printf "\n" }'
    
    echo "};"
    echo ""
    
    # Get file size and add size constant
    local file_size=$(wc -c < "$input_file")
    echo "const size_t $size_name = $file_size;"
}

# Embed the font file from assets/
FONT_FILE="$ASSETS_DIR/default.ttf"
if [ -f "$FONT_FILE" ]; then
    convert_to_c_array "$FONT_FILE" "g_default_font_data" "g_default_font_size" >> "$OUTPUT_FILE"
else
    echo "Error: Font file not found: $FONT_FILE"
    exit 1
fi

# Embed the icon file from assets/
ICON_FILE="$ASSETS_DIR/harmony_icon.png"
if [ -f "$ICON_FILE" ]; then
    echo "" >> "$OUTPUT_FILE"
    convert_to_c_array "$ICON_FILE" "g_app_icon_data" "g_app_icon_size" >> "$OUTPUT_FILE"
else
    echo "Warning: Icon file not found: $ICON_FILE"
fi

# Assets embedded successfully
